language: node_js
node_js:
- 4
- 6
- 8
script:
- npm run build
- npm test
- node_modules/.bin/codecov
deploy:
  provider: npm
  email: karim@alibhai.co
  skip_cleanup: true
  api_key:
    secure: gvMG282Mr5w/5w77TKnWhgJ+jD7ACWSTUsrlJYWWC3v46FX5shjEGCicDGw379sHZVq71LupgKh1Cqi4IbchsocrRsxAGQBvJHTsi5j3E6lYgN7OWtbCUIq9jU2eHzHf9ufBfFTmZnCfFyaahySxMCIKgkpvesv1oNX1ad1qE8YYg5ItvxmdfTvKcCa22Lnx/NMEzeSbJ9FKZ4qmYoxQhIr1FQ7gwMZgtN2SgkmoAUasWJG24rZEGZjfgDGacvA9tRAiWjA99kwr0OV0n9L1EO5R3ObwTs/yAyEfR0LQzZd0SHiIvj12AljaEWkDg3tZ1GOq6rF/B/pUxNdBeuzWxubW5sIe11mq94HY1l2EOLpNk7zvGtENrtpU49Q7ehFZSufjxD8S0/uoNhkMFJDgPF5B1c5c7VFxCxgFMRnQgIsOkoJOT99jTbOiJF2W2pk12L++JrrK/zKzQADOLD1sFTLBJiJB9exd03jsCca8uItihm1UCBDbEcsQogvoP0hPb4RyS6q5UKedrW5qldzs/axDzE2eSSGvU9fzIzK9j4nXiO/NE6jXn9mTZaAfXlzZhY9Oi9xZ0xGTNkDZvjQs6yJMGJdCCA1I9a+reypCepU5w6BcZoV77BFYlV1yg9Xcz14tzgPK/zITIBzDUqRpGQHErh7JrsaCLuFPgF13+DE=
  on:
    tags: true
    repo: karimsa/frenzie
